version: "3.8"

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1323"]
      interval: 30s
      timeout: 10s
      retries: 3
